In [8]:
# Random Numbers
from email.contentmanager import raw_data_manager
import random
a=random.randint(1,10)
a

10

In [9]:
a=random.randrange(1,10)
a

2

In [20]:
a=random.choice('asdjnbfjk')
a

'b'

In [23]:
b=random.sample('abcdefg',3)
b

['f', 'e', 'g']

In [24]:
c=list('abcdefghijklm')
random.shuffle(c)
c

['f', 'k', 'd', 'm', 'l', 'g', 'j', 'e', 'h', 'b', 'a', 'i', 'c']

In [25]:
d=random.seed(1)
random.random()

0.13436424411240122

In [26]:
d=random.seed(1)
random.random()

0.13436424411240122

In [27]:
d=random.seed(2)
random.random()

0.9560342718892494

In [28]:
d=random.seed(3)
random.randint(1,9)

4

In [29]:
d=random.seed(3)
random.randint(1,9)

4

In [30]:
d=random.seed(6)
random.randint(1,9)

2

In [32]:
# Numpy
import numpy as np

In [33]:
a=np.random.rand(3,4)

In [34]:
a

array([[0.3642069 , 0.86118037, 0.25441413, 0.66344182],
       [0.72859481, 0.39084841, 0.59230092, 0.81176682],
       [0.51755297, 0.27096288, 0.17670155, 0.17218266]])

In [38]:
b=np.random.randint(2,7,(3,3),dtype=int)
b


array([[2, 4, 2],
       [4, 6, 3],
       [2, 2, 2]])

In [40]:
c=np.array([[1,2,3],[4,5,6],[2,2,1]])

In [41]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 1]])

In [42]:
np.random.shuffle(c)

In [43]:
c

array([[2, 2, 1],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
# Decorators
def start(func):
    print('hi how r u')
    func()
    print('bye')

@start
def print_name():
    print('alex')

hi how r u
alex
bye


In [46]:
@start
def print_name():
    print('john')

hi how r u
john
bye


In [47]:
def start_end_decorator_3(func):
    
    def wrapper(*args, **kwargs):
        print('Start')
        result = func(*args, **kwargs)
        print('End')
        return result
    return wrapper

@start_end_decorator_3
def add_5(x):
    return x + 5

result = add_5(10)
print(result)

Start
End
15


In [3]:

class CountCalls:

    def __init__(self, func):
        
        self.func = func
        self.num_calls = 0
    
    def __call__(self, *args, **kwargs):
        self.num_calls += 1
        print(f"Call {self.num_calls} of {self.func.__name__!r}")
        return self.func(*args, **kwargs)

@CountCalls
def say_hello(num):
    print("Hello!")
    
say_hello(5)
say_hello(5)     
say_hello(5)  
say_hello(5)  
say_hello(5)                                                                              

Call 1 of 'say_hello'
Hello!
Call 2 of 'say_hello'
Hello!
Call 3 of 'say_hello'
Hello!
Call 4 of 'say_hello'
Hello!
Call 5 of 'say_hello'
Hello!


In [6]:
# Generators
def gen():
    yield 1
    yield 2
    yield 3
g=gen()
next(g)

1

In [7]:

next(g)

2

In [8]:

next(g)

3

In [9]:

next(g)

StopIteration: 

In [10]:
def count(num):
    print('staring')
    while num >0:
        yield num
        num-=1
o=count(6)
next(o)

staring


6

In [11]:
next(o)

5

In [12]:
next(o)


4

In [13]:
next(o)

3

In [14]:
next(o)

2

In [15]:
next(o)

1

In [16]:
next(o)

StopIteration: 

In [19]:
def first(n):
    ns=[]
    num=0
    while n!=num:
        ns.append(num+1)
        num+=1
    return ns

In [20]:
first(9)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
def first(n):
    ns=[]
    num=0
    while n!=num:
        ns.append(num+1)
        yield ns
        num+=1
    

In [22]:
first(4)

<generator object first at 0x00000166797D7680>

In [23]:
def fibonacci(limit):
    a, b = 0, 1
    while a < limit:
        yield a
        a, b = b, a + b

fib = fibonacci(30)

print(list(fib))

[0, 1, 1, 2, 3, 5, 8, 13, 21]


In [24]:
def firstn(n):
    num = 0
    while num < n:
        yield num
        num += 1

sum_of_first_n = sum(firstn(1000000))
print(sum_of_first_n)
import sys
print(sys.getsizeof(firstn(1000000)), "bytes")

499999500000
104 bytes


In [25]:
# threading and multiprocessing
from threading import Thread

def square_numbers():
    for i in range(1000):
        result = i * i

        
if __name__ == "__main__":        
    threads = []
    num_threads = 10

    
    for i in range(num_threads):
        thread = Thread(target=square_numbers)
        threads.append(thread)

  
    for thread in threads:
        thread.start()

 
    for thread in threads:
        thread.join()

In [26]:
from multiprocessing import Process
import os


def square_numbers():
    for i in range(1000):
        result = i * i


if __name__ == "__main__":
    processes = []
    num_processes = os.cpu_count()


    for i in range(num_processes):
        process = Process(target=square_numbers)
        processes.append(process)


    for process in processes:
        process.start()

  
    for process in processes:
        process.join()

In [27]:
import time
def increase(lock):
    global database_value 
    
    with lock: 
        local_copy = database_value
        local_copy += 1
        time.sleep(0.1)
        database_value = local_copy

In [28]:
from queue import Queue

q = Queue()

q.put(1)
q.put(2)
q.put(3) 


first = q.get() 
print(first) 


1


In [29]:
def add_100(number, lock):
    for _ in range(100):
        time.sleep(0.01)
        with lock:
            number.value += 1

In [30]:
from multiprocessing import Queue
q = Queue()

q.put(1)
q.put(2) 
q.put(3) 
first = q.get()
print(first) 

1


In [31]:


from multiprocessing import Pool 

def cube(number):
    return number * number * number

    
if __name__ == "__main__":
    numbers = range(10)
    
    p = Pool()

    result = p.map(cube,  numbers)

    p.close()
    p.join()
    
    print(result)

: 

In [ ]:
# Function and arguments in details

In [1]:
def print_name(name):
    print(name)


print_name("shahid")

shahid


In [2]:
def foot(a,b,c):
    print(a,b,c)


foot(4,5,6)

4 5 6


In [3]:
foot(c=4,a=5,b=6) # key word argument

5 6 4


In [4]:
def foot(a,b,c=100): # default argument
    print(a,b,c)



foot(2,1)


2 1 100


In [11]:
def foot(a,b,*agrs,**kwargs):
    print(a,b)
    for i in agrs:
        print(i)
    for j in kwargs:
        print(j,kwargs[j])

In [13]:
foot(234,56,123,345,6, s=1,w=0)

234 56
123
345
6
s 1
w 0


In [14]:
# unpacking
def foot(a,b,c):
    print(a,b,c)
l=[1,23,345]

foot(*l)

1 23 345


In [16]:
def foot(a,b,c):
    print(a,b,c)
d={'a':93920,'b':384789,'c':100}

foot(**d)

93920 384789 100


In [21]:
# local variable and global variable
def ffo():
 
    num=4
    print('number inside function',num)

num=0
ffo()
print('number out side function',num)

number inside function 4
number out side function 0


In [22]:
num=0
def ffo():
 
    num=4
    print('number inside function',num)

num=0
ffo()
print('number out side function',num)

number inside function 4
number out side function 0


In [23]:
num=0
def ffo():
 

    print('number inside function',num)

num=0
ffo()
print('number out side function',num)

number inside function 0
number out side function 0


In [24]:
def fod(x):
    x=5
var=19
fod(var)
var

19

In [25]:
def foo(a_list):
    a_list += [4, 5]  
def bar(a_list):
    a_list = a_list + [4, 5] 

my_list = [1, 2, 3]
print('my_list before foo():', my_list)
foo(my_list)
print('my_list after foo():', my_list)

my_list = [1, 2, 3]
print('my_list before bar():', my_list)
bar(my_list)
print('my_list after bar():', my_list)

my_list before foo(): [1, 2, 3]
my_list after foo(): [1, 2, 3, 4, 5]
my_list before bar(): [1, 2, 3]
my_list after bar(): [1, 2, 3]


In [26]:
# Asterisk sign (*)
re=23*67
re

1541

In [27]:
9**5

59049

In [28]:
# list
zeros = [0] * 10
onetwos = [1, 2] * 5
print(zeros)
print(onetwos)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


In [29]:
s='abcd' *7

In [30]:
s

'abcdabcdabcdabcdabcdabcdabcd'

In [31]:
a='popopop ' *5

In [32]:
a

'popopop popopop popopop popopop popopop '

In [33]:
def my_function(*args, **kwargs):
    for arg in args:
        print(arg)
    for key in kwargs:
        print(key, kwargs[key])
        
my_function("Hey", 3, [0, 1, 2], name="Alex", age=8)

def my_function2(name, *, age):
    print(name)
    print(age)

my_function2("Michael", age=5)

Hey
3
[0, 1, 2]
name Alex
age 8
Michael
5


In [34]:
# unpacking
def foo(a, b, c):
    print(a, b, c)


my_list = [1, 2, 3]
foo(*my_list)

my_string = "ABC"
foo(*my_string)

my_dict = {'a': 4, 'b': 5, 'c': 6}
foo(**my_dict)

1 2 3
A B C
4 5 6


In [36]:
n=[1,2,3,4,5,88]
*beg,last=n

In [37]:
beg

[1, 2, 3, 4, 5]

In [38]:
last

88

In [39]:
n=[1,2,3,4,5,88]
*beg,second,last=n

In [40]:
beg

[1, 2, 3, 4]

In [41]:
second

5

In [43]:
last

88

In [46]:
da={'a':12,'b': 90}
db={'c':88,'k': 10}
s={**da,**db}

In [47]:
s

{'a': 12, 'b': 90, 'c': 88, 'k': 10}

In [48]:
# deep and shallow copy
ord=[2,3,4]
cp=ord
print(ord)
print(cp)

[2, 3, 4]
[2, 3, 4]


In [49]:
ord=[2,3,4]
cp=ord
cp[0]=-12
print(ord)
print(cp)

[-12, 3, 4]
[-12, 3, 4]


In [50]:
ord=[2,3,4]
cp=ord.copy()
cp[0]=-12
print(ord)
print(cp)

[2, 3, 4]
[-12, 3, 4]


In [51]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
                
# Only copies the reference
p1 = Person('Alex', 27)
p2 = p1
p2.age = 28
print(p1.age)
print(p2.age)

28
28


In [52]:
import copy
p1 = Person('Alex', 27)
p2 = copy.copy(p1)
p2.age = 28
print(p1.age)
print(p2.age)

27
28


In [1]:
# content manager
with open('notes.txt','w') as f:
    f.write('some thing which you')

In [6]:
class managedfile:
    def __init__(self,filename):
        self.name=filename

    def __enter__(self):
        print('enter')
        self.file=open(self.name,'w')
        return self.file
    def __exit__(self,exc_type,exc_value,exc_traceback):
        if self.file:
            self.file.close()
        print( 'exit')

In [7]:
with managedfile('notes.txt') as file:
    file.write('xyz')

enter
exit


In [9]:
from contextlib import contextmanager

@contextmanager
def open_managed_file(filename):
    f = open(filename, 'w')
    try:
        yield f
    finally:
        f.close()
        
with open_managed_file('notes.txt') as f:
    f.write('xyz')
print(f)

<_io.TextIOWrapper name='notes.txt' mode='w' encoding='cp1252'>
